# Generated by Django 5.2 on 2025-05-06 07:20

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.CharField(
                default="Nairobi", max_length=180, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="country",
            field=django_countries.fields.CountryField(
                default="KE", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(
                default="Default description...update me please....",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="plot_area",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=8,
                verbose_name="Plot Area(m^2)",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="postal_code",
            field=models.CharField(
                default="140", max_length=100, verbose_name="Postal Code"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_number",
            field=models.IntegerField(
                default=112,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Property Number",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("House", "House"),
                    ("Apartment", "Apartment"),
                    ("Office", "Office"),
                    ("Warehouse", "Warehouse"),
                    ("Commercial", "Commercial"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
                verbose_name="Property Type",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="street_address",
            field=models.CharField(
                default="KG8 Avenue", max_length=150, verbose_name="Street Address"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="tax",
            field=models.DecimalField(
                decimal_places=2,
                default=0.15,
                help_text="15% property tax charged",
                max_digits=6,
                verbose_name="Property Tax",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="total_floors",
            field=models.IntegerField(default=0, verbose_name="Number of floors"),
        ),
        migrations.AlterField(
            model_name="property",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="agent_buyer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agent,Seller or Buyer",
            ),
        ),
        migrations.AlterField(
            model_name="propertyviews",
            name="ip",
            field=models.CharField(max_length=250, verbose_name="IP Address"),
        ),
        migrations.AlterField(
            model_name="propertyviews",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_views",
                to="properties.property",
            ),
        ),
    ]
